import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Banner from "../components/banner";
import Cart from "../components/cart"

import coffeeStores from "../data/005 coffee-stores.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      <main>
        <Banner/>
        <div className="flex py-16">
      {coffeeStores.map(coffeeStore =>{
        return (
        <Cart
          name = {coffeeStore.name}
          imgUrl = {coffeeStore.imgUrl}
          href = {`/coffe-store/${coffeeStore.id}`}
              
        />
        )
      })}
      </div>
      </main>

     
    </div>
  )
}
